# maum-agit/backend/Dockerfile.dev
# Node.js 20 버전의 경량화된 Alpine 리눅스 이미지 사용
FROM node:20-alpine
# 컨테이너 내부의 작업 디렉토리를 /app으로 설정
WORKDIR /app
# package.json과 package-lock.json 파일을 컨테이너로 복사
COPY package*.json ./
# Node.js 의존성 설치
RUN npm install
# 현재 디렉토리의 모든 파일(소스 코드 포함)을 컨테이너의 /app 디렉토리로 복사
COPY . .
# NestJS 개발 서버의 기본 포트인 3001번을 외부에 노출
EXPOSE 3001
# 컨테이너 실행 시, NestJS 개발 모드 (핫 리로딩) 시작
CMD ["npm", "run", "start:dev"]